# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.static import serve
__author__ = 'wsq'

urlpatterns = patterns('',
                       url(r'^login/static/(?P<path>.*)$', serve, {'document_root':'D:\\huiminyd\static'}),
                       url(r'^connect/static/(?P<path>.*)$', serve, {'document_root':'D:\\huiminyd\static'}),
                       url(r'^$', 'wsq.views.all_goods'),
                       url(r'^all/goods/$', 'wsq.views.all_goods', name='all_goods'),
                       url(r'^one/good/$', 'wsq.views.one_good', name='one_good'),
                       url(r'^no/good/$', 'wsq.views.no_good', name='no_good'),
                       url(r'^add/$', 'wsq.views.add_goods', name="addgoods"),
                       url(r'^add/success/$', 'wsq.views.add_success', name="addsuccess"),
                       url(r'^connect/$', 'wsq.views.connect', name="connect"),
                       url(r'^inbound_channel/$', 'wsq.views.inbound_channel', name="inbound_channel"),
                       url(r'^transfer_shop_manage/$', 'wsq.views.transfer_shop_manage', name="transfer_shop_manage"),
                       url(r'^login/$', 'wsq.views.mylogin', name='mylogin'),
                       url(r'^login/fail$', 'wsq.views.login_fail', name='login_fail'),
                       url(r'^logout/$', 'wsq.views.mylogout', name="logout"),
                       url(r'^api/sell/$', 'wsq.views.api_sell', name="api_sell"),
                       url(r'^api/transfer/$', 'wsq.views.api_transfer', name="api_transfer"),
                       url(r'^api/delete_sell_record/$', 'wsq.views.delete_sell_record', name="delete_sell_record"),
                       url(r'^api/delete_order_record/$', 'wsq.views.delete_order_record', name="delete_order_record"),
                       url(r'^api/add/$', 'wsq.views.api_add', name="api_add"),
                       url(r'^api/sell_info/$', 'wsq.views.api_sell_info', name="api_sell_info"),
                       url(r'^api/order_info/$', 'wsq.views.api_order_info', name="api_order_info"),
                       url(r'^api/update/$', 'wsq.views.api_update', name="api_update"),
                       url(r'^api/update_count/$', 'wsq.views.api_update_count', name="api_update_count"),
                       url(r'^api/delete_inbound', 'wsq.views.delete_inbound', name="delete_inbound"),
                       url(r'^api/delete_goods', 'wsq.views.delete_goods', name="delete_goods"),
                       url(r'^api/delete_transfer_shop', 'wsq.views.delete_transfer_shop', name="delete_transfer_shop"),
                       url(r'^outin/$', 'wsq.views.out_in', name="out_in"),
                       url(r'^out/$', 'wsq.views.out', name="out"),
                       url(r'^in/$', 'wsq.views.in_', name="in"),
                       url(r'^sell_record/$', 'wsq.views.sell_record', name="sell_record"),
                       url(r'^add_record/$', 'wsq.views.add_record', name="add_record"),
                       url(r'^today_profit/$', 'wsq.views.today_profit', name="today_profit"),
                       url(r'^yesterday_profit/$', 'wsq.views.yesterday_profit', name="yesterday_profit"),
                       url(r'^this_month_profit/$', 'wsq.views.this_month_profit', name="this_month_profit"),
                       url(r'^last_month_profit/$', 'wsq.views.last_month_profit', name="last_month_profit"),
                       url(r'^other_month_profit/$', 'wsq.views.other_month_profit', name="other_month_profit"),
                       url(r'^order_manage/$', 'wsq.views.order_manage', name="order_manage"),
                       url(r'^goods_transfer_record/$', 'wsq.views.transfer_record', name="transfer_record"),
                       url(r'^other_cost/$', 'wsq.views.other_cost', name="other_cost"),
                       url(r'^delete_goods/$', 'wsq.views.delete_goods', name="delete_goods"),
                       url(r'^chart/profit/$', 'wsq.views.profit_chart', name="profit_chart"),
                       url(r'^chart/sell_ranking/$', 'wsq.views.sell_ranking_chart', name="sell_ranking_chart"),
                       )